// このファイルは `npm run gen:vvm-catalog` が生成する。手で編集しないこと。
// 生成元: https://raw.githubusercontent.com/VOICEVOX/voicevox_vvm/0.17.0/README.md
import type { VvmCatalogFile, VvmCatalogVoice } from './catalogTypes';

export const VVM_CATALOG_VERSION = "0.17.0";

export const VVM_CATALOG_FILES: Record<string, VvmCatalogFile> = {
  "0.vvm": { size: 59308488, sha256: "ecd35374d4182cd883cba5040376f7f888cc6ba248b1c2f4cea07cdb34bb1318" },
  "1.vvm": { size: 60571189, sha256: "e16ffb6fc3e13e1be4ebc3831cc39df019cbac96b28bbed7653a4bb51c4d7d5d" },
  "2.vvm": { size: 59308683, sha256: "2eb9a67e3bce09a7f209eb21a56926fa94476352b6ce874c9acd8f465871a4f4" },
  "3.vvm": { size: 63346737, sha256: "54aeea4aa51c56e87acc1d406fafc2bd980414c36ebceae0830340b83791d3d7" },
  "4.vvm": { size: 59304904, sha256: "716d2900f6b93ba22119af0e236c32fdbf6fea81c519b5d4830afcb2db349522" },
  "5.vvm": { size: 57611312, sha256: "67451cdbc3e473dba4d09c878903a656be9e7030cb5901155e5a51634ed8b318" },
  "6.vvm": { size: 59304854, sha256: "975d29f225cf605b0e75a0bb66f3f952821b16bbfa49a3a9b96a7688bf21abbe" },
  "7.vvm": { size: 58326212, sha256: "d8e3bc97610805901fb7647226a233fe15056f30d1f91d270895c60198625569" },
  "8.vvm": { size: 59304782, sha256: "0625c497f1f22be87d03281676c0292d834e262338e70ccaf83af7f34aa83b99" },
  "9.vvm": { size: 58328935, sha256: "3dca586c0aa553772419bdc090045f9ea73bd9ed82b88b7dd5737bdd6eddee29" },
  "10.vvm": { size: 58327087, sha256: "dea2104b05391fdc37d8c27b4104569d5bff3a52bcb9e4077bb2b1f951c7524a" },
  "11.vvm": { size: 61687324, sha256: "3fb0c0f12ec37fda568020509d6e63a0a6b5d6edf3c2330508c6bf4e3eeb8b82" },
  "12.vvm": { size: 59305189, sha256: "894464a6cbf59bdf930b8406097f44d2f25bb762db5bc71c9e9c31e1f904c715" },
  "13.vvm": { size: 61686018, sha256: "df381d94df92992c4170017d2f1ca386f7a5c3cb559e1bd0578f899910529e29" },
  "14.vvm": { size: 66281498, sha256: "63cbabeb29ee9a4837a2462c77fc5cecd380abb5bdbcda4c40b3c34f8f2f9d38" },
  "15.vvm": { size: 67265793, sha256: "c29b0c0f8e332fcedc2a5de4b4426feb75fc9f587c314da99af8dbc964287221" },
  "16.vvm": { size: 59303880, sha256: "545a2365dbb3f457d2ee9e24b45313968aa4c8351d513f3a79d9922a17569cab" },
  "17.vvm": { size: 59304258, sha256: "eb96b6c71fa80f905a86ec7f221f10fbf31f84c0675f919a25d198d8561e3f9a" },
  "18.vvm": { size: 62519486, sha256: "33e5177ebbe1ec5829769c1017f1294641dbf22c43cd2af4896ae0738a14ed13" },
  "19.vvm": { size: 60021787, sha256: "b9e1c5ddd5b418a6f1d6377d7d00df32c682b580ac9d326675ba4e0b7bb4fc3d" },
  "20.vvm": { size: 60535324, sha256: "fcfa6438d71df86c2013a8f285224fb96b632c4f07486d9855474f3df9a50a09" },
  "21.vvm": { size: 63195138, sha256: "f6b937e953409a65f3d7609335a4dfd19fdd9458be27d988bdd8296034adfaf6" },
  "22.vvm": { size: 63409684, sha256: "1c580f93caaa89f517d2431ee82519eab39c389d1bfb8791035f5c5af71eb17d" },
  "23.vvm": { size: 60022581, sha256: "4e09d14a73e5c3e6ec237cf37aae1ce44464e0d4b8a36e7580cb7b475f494dda" },
  "24.vvm": { size: 60024319, sha256: "3e62f5ce0ac345ed74c0e3bc9051cd99baaed37389e33f64195c9e0e49f34594" },
  "n0.vvm": { size: 75175864, sha256: "f9793559a0ecad1622c15e68674860d7d00ce2736cf02b3f46b083e989c74ec7" },
  "s0.vvm": { size: 130412376, sha256: "e97971e3d9c0feaf7a373a5b13b905a885731ce61eef489857055a6631030038" },
};

export const VVM_CATALOG_VOICES: VvmCatalogVoice[] = [
  { character: "aierutan", style: "normal", file: "14.vvm", styleId: 68, kind: "talk", characterName: "あいえるたん", styleName: "ノーマル" },
  { character: "aierutan", style: "normal", file: "s0.vvm", styleId: 3068, kind: "song", characterName: "あいえるたん", styleName: "ノーマル" },
  { character: "akatsuki_mitama", style: "normal", file: "24.vvm", styleId: 122, kind: "talk", characterName: "暁記ミタマ", styleName: "ノーマル" },
  { character: "akatsuki_mitama", style: "ikari", file: "24.vvm", styleId: 123, kind: "talk", characterName: "暁記ミタマ", styleName: "怒り" },
  { character: "akatsuki_mitama", style: "kanashimi", file: "24.vvm", styleId: 124, kind: "talk", characterName: "暁記ミタマ", styleName: "哀しみ" },
  { character: "akatsuki_mitama", style: "sasayaki", file: "24.vvm", styleId: 125, kind: "talk", characterName: "暁記ミタマ", styleName: "ささやき" },
  { character: "amehare_hau", style: "normal", file: "0.vvm", styleId: 10, kind: "talk", characterName: "雨晴はう", styleName: "ノーマル" },
  { character: "amehare_hau", style: "normal", file: "s0.vvm", styleId: 3010, kind: "song", characterName: "雨晴はう", styleName: "ノーマル" },
  { character: "ankomon", style: "normal", file: "22.vvm", styleId: 113, kind: "talk", characterName: "あんこもん", styleName: "ノーマル" },
  { character: "ankomon", style: "tsuyotsuyo", file: "22.vvm", styleId: 114, kind: "talk", characterName: "あんこもん", styleName: "つよつよ" },
  { character: "ankomon", style: "yowayowa", file: "22.vvm", styleId: 115, kind: "talk", characterName: "あんこもん", styleName: "よわよわ" },
  { character: "ankomon", style: "kedaruge", file: "22.vvm", styleId: 116, kind: "talk", characterName: "あんこもん", styleName: "けだるげ" },
  { character: "ankomon", style: "sasayaki", file: "23.vvm", styleId: 117, kind: "talk", characterName: "あんこもん", styleName: "ささやき" },
  { character: "aoyama_ryusei", style: "normal", file: "15.vvm", styleId: 13, kind: "talk", characterName: "青山龍星", styleName: "ノーマル" },
  { character: "aoyama_ryusei", style: "nekketsu", file: "15.vvm", styleId: 81, kind: "talk", characterName: "青山龍星", styleName: "熱血" },
  { character: "aoyama_ryusei", style: "fukigen", file: "15.vvm", styleId: 82, kind: "talk", characterName: "青山龍星", styleName: "不機嫌" },
  { character: "aoyama_ryusei", style: "yorokobi", file: "15.vvm", styleId: 83, kind: "talk", characterName: "青山龍星", styleName: "喜び" },
  { character: "aoyama_ryusei", style: "shittori", file: "15.vvm", styleId: 84, kind: "talk", characterName: "青山龍星", styleName: "しっとり" },
  { character: "aoyama_ryusei", style: "kanashimi", file: "15.vvm", styleId: 85, kind: "talk", characterName: "青山龍星", styleName: "かなしみ" },
  { character: "aoyama_ryusei", style: "sasayaki", file: "15.vvm", styleId: 86, kind: "talk", characterName: "青山龍星", styleName: "囁き" },
  { character: "aoyama_ryusei", style: "normal", file: "s0.vvm", styleId: 3013, kind: "song", characterName: "青山龍星", styleName: "ノーマル" },
  { character: "aoyama_ryusei", style: "nekketsu", file: "s0.vvm", styleId: 3081, kind: "song", characterName: "青山龍星", styleName: "熱血" },
  { character: "aoyama_ryusei", style: "fukigen", file: "s0.vvm", styleId: 3082, kind: "song", characterName: "青山龍星", styleName: "不機嫌" },
  { character: "aoyama_ryusei", style: "yorokobi", file: "s0.vvm", styleId: 3083, kind: "song", characterName: "青山龍星", styleName: "喜び" },
  { character: "aoyama_ryusei", style: "shittori", file: "s0.vvm", styleId: 3084, kind: "song", characterName: "青山龍星", styleName: "しっとり" },
  { character: "aoyama_ryusei", style: "kanashimi", file: "s0.vvm", styleId: 3085, kind: "song", characterName: "青山龍星", styleName: "かなしみ" },
  { character: "chibishikiji", style: "normal", file: "10.vvm", styleId: 42, kind: "talk", characterName: "ちび式じい", styleName: "ノーマル" },
  { character: "chibishikiji", style: "normal", file: "s0.vvm", styleId: 3042, kind: "song", characterName: "ちび式じい", styleName: "ノーマル" },
  { character: "chubu_tsurugi", style: "normal", file: "18.vvm", styleId: 94, kind: "talk", characterName: "中部つるぎ", styleName: "ノーマル" },
  { character: "chubu_tsurugi", style: "ikari", file: "18.vvm", styleId: 95, kind: "talk", characterName: "中部つるぎ", styleName: "怒り" },
  { character: "chubu_tsurugi", style: "hisohiso", file: "18.vvm", styleId: 96, kind: "talk", characterName: "中部つるぎ", styleName: "ヒソヒソ" },
  { character: "chubu_tsurugi", style: "odoodo", file: "18.vvm", styleId: 97, kind: "talk", characterName: "中部つるぎ", styleName: "おどおど" },
  { character: "chubu_tsurugi", style: "zetsubo_to_haiboku", file: "18.vvm", styleId: 98, kind: "talk", characterName: "中部つるぎ", styleName: "絶望と敗北" },
  { character: "chugoku_usagi", style: "normal", file: "3.vvm", styleId: 61, kind: "talk", characterName: "中国うさぎ", styleName: "ノーマル" },
  { character: "chugoku_usagi", style: "odoroki", file: "3.vvm", styleId: 62, kind: "talk", characterName: "中国うさぎ", styleName: "おどろき" },
  { character: "chugoku_usagi", style: "kowagari", file: "3.vvm", styleId: 63, kind: "talk", characterName: "中国うさぎ", styleName: "こわがり" },
  { character: "chugoku_usagi", style: "herohero", file: "3.vvm", styleId: 64, kind: "talk", characterName: "中国うさぎ", styleName: "へろへろ" },
  { character: "chugoku_usagi", style: "normal", file: "s0.vvm", styleId: 3061, kind: "song", characterName: "中国うさぎ", styleName: "ノーマル" },
  { character: "chugoku_usagi", style: "odoroki", file: "s0.vvm", styleId: 3062, kind: "song", characterName: "中国うさぎ", styleName: "おどろき" },
  { character: "chugoku_usagi", style: "kowagari", file: "s0.vvm", styleId: 3063, kind: "song", characterName: "中国うさぎ", styleName: "こわがり" },
  { character: "chugoku_usagi", style: "herohero", file: "s0.vvm", styleId: 3064, kind: "song", characterName: "中国うさぎ", styleName: "へろへろ" },
  { character: "goki", style: "ningen", file: "7.vvm", styleId: 27, kind: "talk", characterName: "後鬼", styleName: "人間ver." },
  { character: "goki", style: "nuigurumi", file: "7.vvm", styleId: 28, kind: "talk", characterName: "後鬼", styleName: "ぬいぐるみver." },
  { character: "goki", style: "ningen_ikari", file: "16.vvm", styleId: 87, kind: "talk", characterName: "後鬼", styleName: "人間（怒り）ver." },
  { character: "goki", style: "oni", file: "16.vvm", styleId: 88, kind: "talk", characterName: "後鬼", styleName: "鬼ver." },
  { character: "goki", style: "ningen", file: "s0.vvm", styleId: 3027, kind: "song", characterName: "後鬼", styleName: "人間ver." },
  { character: "goki", style: "nuigurumi", file: "s0.vvm", styleId: 3028, kind: "song", characterName: "後鬼", styleName: "ぬいぐるみver." },
  { character: "haruka_nana", style: "normal", file: "13.vvm", styleId: 54, kind: "talk", characterName: "春歌ナナ", styleName: "ノーマル" },
  { character: "haruka_nana", style: "normal", file: "s0.vvm", styleId: 3054, kind: "song", characterName: "春歌ナナ", styleName: "ノーマル" },
  { character: "horinaito_benizakura", style: "normal", file: "12.vvm", styleId: 51, kind: "talk", characterName: "†聖騎士 紅桜†", styleName: "ノーマル" },
  { character: "horinaito_benizakura", style: "normal", file: "s0.vvm", styleId: 3051, kind: "song", characterName: "†聖騎士 紅桜†", styleName: "ノーマル" },
  { character: "kasukabe_tsumugi", style: "normal", file: "0.vvm", styleId: 8, kind: "talk", characterName: "春日部つむぎ", styleName: "ノーマル" },
  { character: "kasukabe_tsumugi", style: "normal", file: "s0.vvm", styleId: 3008, kind: "song", characterName: "春日部つむぎ", styleName: "ノーマル" },
  { character: "kenzaki_mesuo", style: "normal", file: "4.vvm", styleId: 21, kind: "talk", characterName: "剣崎雌雄", styleName: "ノーマル" },
  { character: "kenzaki_mesuo", style: "normal", file: "s0.vvm", styleId: 3021, kind: "song", characterName: "剣崎雌雄", styleName: "ノーマル" },
  { character: "kigashima_sourin", style: "normal", file: "12.vvm", styleId: 53, kind: "talk", characterName: "麒ヶ島宗麟", styleName: "ノーマル" },
  { character: "kigashima_sourin", style: "normal", file: "s0.vvm", styleId: 3053, kind: "song", characterName: "麒ヶ島宗麟", styleName: "ノーマル" },
  { character: "kotoyomi_nia", style: "normal", file: "14.vvm", styleId: 74, kind: "talk", characterName: "琴詠ニア", styleName: "ノーマル" },
  { character: "kotoyomi_nia", style: "normal", file: "s0.vvm", styleId: 3074, kind: "song", characterName: "琴詠ニア", styleName: "ノーマル" },
  { character: "kurita_maron", style: "normal", file: "14.vvm", styleId: 67, kind: "talk", characterName: "栗田まろん", styleName: "ノーマル" },
  { character: "kurita_maron", style: "normal", file: "s0.vvm", styleId: 3067, kind: "song", characterName: "栗田まろん", styleName: "ノーマル" },
  { character: "kurono_takehiro", style: "normal", file: "4.vvm", styleId: 11, kind: "talk", characterName: "玄野武宏", styleName: "ノーマル" },
  { character: "kurono_takehiro", style: "yorokobi", file: "10.vvm", styleId: 39, kind: "talk", characterName: "玄野武宏", styleName: "喜び" },
  { character: "kurono_takehiro", style: "tsungire", file: "10.vvm", styleId: 40, kind: "talk", characterName: "玄野武宏", styleName: "ツンギレ" },
  { character: "kurono_takehiro", style: "kanashimi", file: "10.vvm", styleId: 41, kind: "talk", characterName: "玄野武宏", styleName: "悲しみ" },
  { character: "kurono_takehiro", style: "normal", file: "s0.vvm", styleId: 3011, kind: "song", characterName: "玄野武宏", styleName: "ノーマル" },
  { character: "kurono_takehiro", style: "yorokobi", file: "s0.vvm", styleId: 3039, kind: "song", characterName: "玄野武宏", styleName: "喜び" },
  { character: "kurono_takehiro", style: "tsungire", file: "s0.vvm", styleId: 3040, kind: "song", characterName: "玄野武宏", styleName: "ツンギレ" },
  { character: "kurono_takehiro", style: "kanashimi", file: "s0.vvm", styleId: 3041, kind: "song", characterName: "玄野武宏", styleName: "悲しみ" },
  { character: "kurosawa_kohaku", style: "normal", file: "19.vvm", styleId: 100, kind: "talk", characterName: "黒沢冴白", styleName: "ノーマル" },
  { character: "kyushu_sora", style: "amaama", file: "2.vvm", styleId: 15, kind: "talk", characterName: "九州そら", styleName: "あまあま" },
  { character: "kyushu_sora", style: "normal", file: "2.vvm", styleId: 16, kind: "talk", characterName: "九州そら", styleName: "ノーマル" },
  { character: "kyushu_sora", style: "sexy", file: "2.vvm", styleId: 17, kind: "talk", characterName: "九州そら", styleName: "セクシー" },
  { character: "kyushu_sora", style: "tsuntsun", file: "2.vvm", styleId: 18, kind: "talk", characterName: "九州そら", styleName: "ツンツン" },
  { character: "kyushu_sora", style: "sasayaki", file: "5.vvm", styleId: 19, kind: "talk", characterName: "九州そら", styleName: "ささやき" },
  { character: "kyushu_sora", style: "amaama", file: "s0.vvm", styleId: 3015, kind: "song", characterName: "九州そら", styleName: "あまあま" },
  { character: "kyushu_sora", style: "normal", file: "s0.vvm", styleId: 3016, kind: "song", characterName: "九州そら", styleName: "ノーマル" },
  { character: "kyushu_sora", style: "sexy", file: "s0.vvm", styleId: 3017, kind: "song", characterName: "九州そら", styleName: "セクシー" },
  { character: "kyushu_sora", style: "tsuntsun", file: "s0.vvm", styleId: 3018, kind: "song", characterName: "九州そら", styleName: "ツンツン" },
  { character: "manbetsu_hanamaru", style: "normal", file: "14.vvm", styleId: 69, kind: "talk", characterName: "満別花丸", styleName: "ノーマル" },
  { character: "manbetsu_hanamaru", style: "genki", file: "14.vvm", styleId: 70, kind: "talk", characterName: "満別花丸", styleName: "元気" },
  { character: "manbetsu_hanamaru", style: "sasayaki", file: "14.vvm", styleId: 71, kind: "talk", characterName: "満別花丸", styleName: "ささやき" },
  { character: "manbetsu_hanamaru", style: "burikko", file: "14.vvm", styleId: 72, kind: "talk", characterName: "満別花丸", styleName: "ぶりっ子" },
  { character: "manbetsu_hanamaru", style: "boy", file: "14.vvm", styleId: 73, kind: "talk", characterName: "満別花丸", styleName: "ボーイ" },
  { character: "manbetsu_hanamaru", style: "normal", file: "s0.vvm", styleId: 3069, kind: "song", characterName: "満別花丸", styleName: "ノーマル" },
  { character: "manbetsu_hanamaru", style: "genki", file: "s0.vvm", styleId: 3070, kind: "song", characterName: "満別花丸", styleName: "元気" },
  { character: "manbetsu_hanamaru", style: "sasayaki", file: "s0.vvm", styleId: 3071, kind: "song", characterName: "満別花丸", styleName: "ささやき" },
  { character: "manbetsu_hanamaru", style: "burikko", file: "s0.vvm", styleId: 3072, kind: "song", characterName: "満別花丸", styleName: "ぶりっ子" },
  { character: "manbetsu_hanamaru", style: "boy", file: "s0.vvm", styleId: 3073, kind: "song", characterName: "満別花丸", styleName: "ボーイ" },
  { character: "meimei_himari", style: "normal", file: "1.vvm", styleId: 14, kind: "talk", characterName: "冥鳴ひまり", styleName: "ノーマル" },
  { character: "meimei_himari", style: "normal", file: "s0.vvm", styleId: 3014, kind: "song", characterName: "冥鳴ひまり", styleName: "ノーマル" },
  { character: "mochikosan", style: "normal", file: "15.vvm", styleId: 20, kind: "talk", characterName: "もち子さん", styleName: "ノーマル" },
  { character: "mochikosan", style: "sexy_anko", file: "15.vvm", styleId: 66, kind: "talk", characterName: "もち子さん", styleName: "セクシー／あん子" },
  { character: "mochikosan", style: "naki", file: "15.vvm", styleId: 77, kind: "talk", characterName: "もち子さん", styleName: "泣き" },
  { character: "mochikosan", style: "ikari", file: "15.vvm", styleId: 78, kind: "talk", characterName: "もち子さん", styleName: "怒り" },
  { character: "mochikosan", style: "yorokobi", file: "15.vvm", styleId: 79, kind: "talk", characterName: "もち子さん", styleName: "喜び" },
  { character: "mochikosan", style: "nonbiri", file: "15.vvm", styleId: 80, kind: "talk", characterName: "もち子さん", styleName: "のんびり" },
  { character: "mochikosan", style: "normal", file: "s0.vvm", styleId: 3020, kind: "song", characterName: "もち子さん", styleName: "ノーマル" },
  { character: "mochikosan", style: "sexy_anko", file: "s0.vvm", styleId: 3066, kind: "song", characterName: "もち子さん", styleName: "セクシー／あん子" },
  { character: "mochikosan", style: "naki", file: "s0.vvm", styleId: 3077, kind: "song", characterName: "もち子さん", styleName: "泣き" },
  { character: "mochikosan", style: "ikari", file: "s0.vvm", styleId: 3078, kind: "song", characterName: "もち子さん", styleName: "怒り" },
  { character: "mochikosan", style: "yorokobi", file: "s0.vvm", styleId: 3079, kind: "song", characterName: "もち子さん", styleName: "喜び" },
  { character: "mochikosan", style: "nonbiri", file: "s0.vvm", styleId: 3080, kind: "song", characterName: "もち子さん", styleName: "のんびり" },
  { character: "namine_ritsu", style: "normal", file: "3.vvm", styleId: 9, kind: "talk", characterName: "波音リツ", styleName: "ノーマル" },
  { character: "namine_ritsu", style: "queen", file: "3.vvm", styleId: 65, kind: "talk", characterName: "波音リツ", styleName: "クイーン" },
  { character: "namine_ritsu", style: "normal", file: "s0.vvm", styleId: 3009, kind: "song", characterName: "波音リツ", styleName: "ノーマル" },
  { character: "namine_ritsu", style: "queen", file: "s0.vvm", styleId: 3065, kind: "song", characterName: "波音リツ", styleName: "クイーン" },
  { character: "namine_ritsu", style: "normal", file: "s0.vvm", styleId: 6000, kind: "song", characterName: "波音リツ", styleName: "ノーマル" },
  { character: "nekotsuka_aru", style: "normal", file: "13.vvm", styleId: 55, kind: "talk", characterName: "猫使アル", styleName: "ノーマル" },
  { character: "nekotsuka_aru", style: "ochitsuki", file: "13.vvm", styleId: 56, kind: "talk", characterName: "猫使アル", styleName: "おちつき" },
  { character: "nekotsuka_aru", style: "ukiuki", file: "13.vvm", styleId: 57, kind: "talk", characterName: "猫使アル", styleName: "うきうき" },
  { character: "nekotsuka_aru", style: "tsuyotsuyo", file: "21.vvm", styleId: 110, kind: "talk", characterName: "猫使アル", styleName: "つよつよ" },
  { character: "nekotsuka_aru", style: "herohero", file: "21.vvm", styleId: 111, kind: "talk", characterName: "猫使アル", styleName: "へろへろ" },
  { character: "nekotsuka_aru", style: "normal", file: "s0.vvm", styleId: 3055, kind: "song", characterName: "猫使アル", styleName: "ノーマル" },
  { character: "nekotsuka_aru", style: "ochitsuki", file: "s0.vvm", styleId: 3056, kind: "song", characterName: "猫使アル", styleName: "おちつき" },
  { character: "nekotsuka_aru", style: "ukiuki", file: "s0.vvm", styleId: 3057, kind: "song", characterName: "猫使アル", styleName: "うきうき" },
  { character: "nekotsuka_bi", style: "normal", file: "13.vvm", styleId: 58, kind: "talk", characterName: "猫使ビィ", styleName: "ノーマル" },
  { character: "nekotsuka_bi", style: "ochitsuki", file: "13.vvm", styleId: 59, kind: "talk", characterName: "猫使ビィ", styleName: "おちつき" },
  { character: "nekotsuka_bi", style: "hitomishiri", file: "13.vvm", styleId: 60, kind: "talk", characterName: "猫使ビィ", styleName: "人見知り" },
  { character: "nekotsuka_bi", style: "tsuyotsuyo", file: "21.vvm", styleId: 112, kind: "talk", characterName: "猫使ビィ", styleName: "つよつよ" },
  { character: "nekotsuka_bi", style: "normal", file: "s0.vvm", styleId: 3058, kind: "song", characterName: "猫使ビィ", styleName: "ノーマル" },
  { character: "nekotsuka_bi", style: "ochitsuki", file: "s0.vvm", styleId: 3059, kind: "song", characterName: "猫使ビィ", styleName: "おちつき" },
  { character: "nemo_female_1", style: "normal", file: "n0.vvm", styleId: 10005, kind: "nemo", characterName: "女声1", styleName: "ノーマル" },
  { character: "nemo_female_2", style: "normal", file: "n0.vvm", styleId: 10007, kind: "nemo", characterName: "女声2", styleName: "ノーマル" },
  { character: "nemo_female_3", style: "normal", file: "n0.vvm", styleId: 10004, kind: "nemo", characterName: "女声3", styleName: "ノーマル" },
  { character: "nemo_female_4", style: "normal", file: "n0.vvm", styleId: 10003, kind: "nemo", characterName: "女声4", styleName: "ノーマル" },
  { character: "nemo_female_5", style: "normal", file: "n0.vvm", styleId: 10008, kind: "nemo", characterName: "女声5", styleName: "ノーマル" },
  { character: "nemo_female_6", style: "normal", file: "n0.vvm", styleId: 10006, kind: "nemo", characterName: "女声6", styleName: "ノーマル" },
  { character: "nemo_male_1", style: "normal", file: "n0.vvm", styleId: 10001, kind: "nemo", characterName: "男声1", styleName: "ノーマル" },
  { character: "nemo_male_2", style: "normal", file: "n0.vvm", styleId: 10000, kind: "nemo", characterName: "男声2", styleName: "ノーマル" },
  { character: "nemo_male_3", style: "normal", file: "n0.vvm", styleId: 10002, kind: "nemo", characterName: "男声3", styleName: "ノーマル" },
  { character: "number_seven", style: "normal", file: "6.vvm", styleId: 29, kind: "talk", characterName: "No.7", styleName: "ノーマル" },
  { character: "number_seven", style: "announce", file: "6.vvm", styleId: 30, kind: "talk", characterName: "No.7", styleName: "アナウンス" },
  { character: "number_seven", style: "yomikikase", file: "6.vvm", styleId: 31, kind: "talk", characterName: "No.7", styleName: "読み聞かせ" },
  { character: "number_seven", style: "normal", file: "s0.vvm", styleId: 3029, kind: "song", characterName: "No.7", styleName: "ノーマル" },
  { character: "number_seven", style: "announce", file: "s0.vvm", styleId: 3030, kind: "song", characterName: "No.7", styleName: "アナウンス" },
  { character: "number_seven", style: "yomikikase", file: "s0.vvm", styleId: 3031, kind: "song", characterName: "No.7", styleName: "読み聞かせ" },
  { character: "nurserobo_typet", style: "normal", file: "11.vvm", styleId: 47, kind: "talk", characterName: "ナースロボ＿タイプＴ", styleName: "ノーマル" },
  { character: "nurserobo_typet", style: "rakuraku", file: "11.vvm", styleId: 48, kind: "talk", characterName: "ナースロボ＿タイプＴ", styleName: "楽々" },
  { character: "nurserobo_typet", style: "kyofu", file: "11.vvm", styleId: 49, kind: "talk", characterName: "ナースロボ＿タイプＴ", styleName: "恐怖" },
  { character: "nurserobo_typet", style: "naishobanashi", file: "11.vvm", styleId: 50, kind: "talk", characterName: "ナースロボ＿タイプＴ", styleName: "内緒話" },
  { character: "nurserobo_typet", style: "normal", file: "s0.vvm", styleId: 3047, kind: "song", characterName: "ナースロボ＿タイプＴ", styleName: "ノーマル" },
  { character: "nurserobo_typet", style: "rakuraku", file: "s0.vvm", styleId: 3048, kind: "song", characterName: "ナースロボ＿タイプＴ", styleName: "楽々" },
  { character: "nurserobo_typet", style: "kyofu", file: "s0.vvm", styleId: 3049, kind: "song", characterName: "ナースロボ＿タイプＴ", styleName: "恐怖" },
  { character: "ouka_miko", style: "normal", file: "11.vvm", styleId: 43, kind: "talk", characterName: "櫻歌ミコ", styleName: "ノーマル" },
  { character: "ouka_miko", style: "daini_keitai", file: "11.vvm", styleId: 44, kind: "talk", characterName: "櫻歌ミコ", styleName: "第二形態" },
  { character: "ouka_miko", style: "loli", file: "11.vvm", styleId: 45, kind: "talk", characterName: "櫻歌ミコ", styleName: "ロリ" },
  { character: "ouka_miko", style: "normal", file: "s0.vvm", styleId: 3043, kind: "song", characterName: "櫻歌ミコ", styleName: "ノーマル" },
  { character: "ouka_miko", style: "daini_keitai", file: "s0.vvm", styleId: 3044, kind: "song", characterName: "櫻歌ミコ", styleName: "第二形態" },
  { character: "ouka_miko", style: "loli", file: "s0.vvm", styleId: 3045, kind: "song", characterName: "櫻歌ミコ", styleName: "ロリ" },
  { character: "rito", style: "normal", file: "19.vvm", styleId: 99, kind: "talk", characterName: "離途", styleName: "ノーマル" },
  { character: "rito", style: "serious", file: "19.vvm", styleId: 101, kind: "talk", characterName: "離途", styleName: "シリアス" },
  { character: "satoishi_yuka", style: "tsubomi", file: "24.vvm", styleId: 126, kind: "talk", characterName: "里石ユカ", styleName: "つぼみ" },
  { character: "sayo", style: "normal", file: "15.vvm", styleId: 46, kind: "talk", characterName: "小夜/SAYO", styleName: "ノーマル" },
  { character: "sayo", style: "normal", file: "s0.vvm", styleId: 3046, kind: "song", characterName: "小夜/SAYO", styleName: "ノーマル" },
  { character: "shikoku_metan", style: "amaama", file: "0.vvm", styleId: 0, kind: "talk", characterName: "四国めたん", styleName: "あまあま" },
  { character: "shikoku_metan", style: "normal", file: "0.vvm", styleId: 2, kind: "talk", characterName: "四国めたん", styleName: "ノーマル" },
  { character: "shikoku_metan", style: "sexy", file: "0.vvm", styleId: 4, kind: "talk", characterName: "四国めたん", styleName: "セクシー" },
  { character: "shikoku_metan", style: "tsuntsun", file: "0.vvm", styleId: 6, kind: "talk", characterName: "四国めたん", styleName: "ツンツン" },
  { character: "shikoku_metan", style: "sasayaki", file: "5.vvm", styleId: 36, kind: "talk", characterName: "四国めたん", styleName: "ささやき" },
  { character: "shikoku_metan", style: "hisohiso", file: "5.vvm", styleId: 37, kind: "talk", characterName: "四国めたん", styleName: "ヒソヒソ" },
  { character: "shikoku_metan", style: "amaama", file: "s0.vvm", styleId: 3000, kind: "song", characterName: "四国めたん", styleName: "あまあま" },
  { character: "shikoku_metan", style: "normal", file: "s0.vvm", styleId: 3002, kind: "song", characterName: "四国めたん", styleName: "ノーマル" },
  { character: "shikoku_metan", style: "sexy", file: "s0.vvm", styleId: 3004, kind: "song", characterName: "四国めたん", styleName: "セクシー" },
  { character: "shikoku_metan", style: "tsuntsun", file: "s0.vvm", styleId: 3006, kind: "song", characterName: "四国めたん", styleName: "ツンツン" },
  { character: "shikoku_metan", style: "hisohiso", file: "s0.vvm", styleId: 3037, kind: "song", characterName: "四国めたん", styleName: "ヒソヒソ" },
  { character: "shirakami_kotarou", style: "futsuu", file: "9.vvm", styleId: 12, kind: "talk", characterName: "白上虎太郎", styleName: "ふつう" },
  { character: "shirakami_kotarou", style: "waai", file: "9.vvm", styleId: 32, kind: "talk", characterName: "白上虎太郎", styleName: "わーい" },
  { character: "shirakami_kotarou", style: "bikubiku", file: "9.vvm", styleId: 33, kind: "talk", characterName: "白上虎太郎", styleName: "びくびく" },
  { character: "shirakami_kotarou", style: "oko", file: "9.vvm", styleId: 34, kind: "talk", characterName: "白上虎太郎", styleName: "おこ" },
  { character: "shirakami_kotarou", style: "bieen", file: "9.vvm", styleId: 35, kind: "talk", characterName: "白上虎太郎", styleName: "びえーん" },
  { character: "shirakami_kotarou", style: "futsuu", file: "s0.vvm", styleId: 3012, kind: "song", characterName: "白上虎太郎", styleName: "ふつう" },
  { character: "shirakami_kotarou", style: "waai", file: "s0.vvm", styleId: 3032, kind: "song", characterName: "白上虎太郎", styleName: "わーい" },
  { character: "shirakami_kotarou", style: "bikubiku", file: "s0.vvm", styleId: 3033, kind: "song", characterName: "白上虎太郎", styleName: "びくびく" },
  { character: "shirakami_kotarou", style: "oko", file: "s0.vvm", styleId: 3034, kind: "song", characterName: "白上虎太郎", styleName: "おこ" },
  { character: "shirakami_kotarou", style: "bieen", file: "s0.vvm", styleId: 3035, kind: "song", characterName: "白上虎太郎", styleName: "びえーん" },
  { character: "tohoku_itako", style: "normal", file: "21.vvm", styleId: 109, kind: "talk", characterName: "東北イタコ", styleName: "ノーマル" },
  { character: "tohoku_kiritan", style: "normal", file: "21.vvm", styleId: 108, kind: "talk", characterName: "東北きりたん", styleName: "ノーマル" },
  { character: "tohoku_zunko", style: "normal", file: "21.vvm", styleId: 107, kind: "talk", characterName: "東北ずん子", styleName: "ノーマル" },
  { character: "voidoll", style: "normal", file: "17.vvm", styleId: 89, kind: "talk", characterName: "Voidoll", styleName: "ノーマル" },
  { character: "wakamatsu_akashi", style: "normal", file: "12.vvm", styleId: 52, kind: "talk", characterName: "雀松朱司", styleName: "ノーマル" },
  { character: "wakamatsu_akashi", style: "normal", file: "s0.vvm", styleId: 3052, kind: "song", characterName: "雀松朱司", styleName: "ノーマル" },
  { character: "white_cul", style: "normal", file: "8.vvm", styleId: 23, kind: "talk", characterName: "WhiteCUL", styleName: "ノーマル" },
  { character: "white_cul", style: "tanoshii", file: "8.vvm", styleId: 24, kind: "talk", characterName: "WhiteCUL", styleName: "たのしい" },
  { character: "white_cul", style: "kanashii", file: "8.vvm", styleId: 25, kind: "talk", characterName: "WhiteCUL", styleName: "かなしい" },
  { character: "white_cul", style: "bieen", file: "8.vvm", styleId: 26, kind: "talk", characterName: "WhiteCUL", styleName: "びえーん" },
  { character: "white_cul", style: "normal", file: "s0.vvm", styleId: 3023, kind: "song", characterName: "WhiteCUL", styleName: "ノーマル" },
  { character: "white_cul", style: "tanoshii", file: "s0.vvm", styleId: 3024, kind: "song", characterName: "WhiteCUL", styleName: "たのしい" },
  { character: "white_cul", style: "kanashii", file: "s0.vvm", styleId: 3025, kind: "song", characterName: "WhiteCUL", styleName: "かなしい" },
  { character: "white_cul", style: "bieen", file: "s0.vvm", styleId: 3026, kind: "song", characterName: "WhiteCUL", styleName: "びえーん" },
  { character: "yogatari_tobari", style: "normal", file: "24.vvm", styleId: 118, kind: "talk", characterName: "夜語トバリ", styleName: "ノーマル" },
  { character: "yogatari_tobari", style: "akarui", file: "24.vvm", styleId: 119, kind: "talk", characterName: "夜語トバリ", styleName: "明るい" },
  { character: "yogatari_tobari", style: "kanashimi", file: "24.vvm", styleId: 120, kind: "talk", characterName: "夜語トバリ", styleName: "哀しみ" },
  { character: "yogatari_tobari", style: "akire", file: "24.vvm", styleId: 121, kind: "talk", characterName: "夜語トバリ", styleName: "呆れ" },
  { character: "yureichan", style: "normal", file: "20.vvm", styleId: 102, kind: "talk", characterName: "ユーレイちゃん", styleName: "ノーマル" },
  { character: "yureichan", style: "amaama", file: "20.vvm", styleId: 103, kind: "talk", characterName: "ユーレイちゃん", styleName: "甘々" },
  { character: "yureichan", style: "kanashimi", file: "20.vvm", styleId: 104, kind: "talk", characterName: "ユーレイちゃん", styleName: "哀しみ" },
  { character: "yureichan", style: "sasayaki", file: "20.vvm", styleId: 105, kind: "talk", characterName: "ユーレイちゃん", styleName: "ささやき" },
  { character: "yureichan", style: "tsukumochan", file: "20.vvm", styleId: 106, kind: "talk", characterName: "ユーレイちゃん", styleName: "ツクモちゃん" },
  { character: "zonko", style: "normal", file: "18.vvm", styleId: 90, kind: "talk", characterName: "ぞん子", styleName: "ノーマル" },
  { character: "zonko", style: "teiketsuatsu", file: "18.vvm", styleId: 91, kind: "talk", characterName: "ぞん子", styleName: "低血圧" },
  { character: "zonko", style: "kakusei", file: "18.vvm", styleId: 92, kind: "talk", characterName: "ぞん子", styleName: "覚醒" },
  { character: "zonko", style: "jikkyofu", file: "18.vvm", styleId: 93, kind: "talk", characterName: "ぞん子", styleName: "実況風" },
  { character: "zundamon", style: "amaama", file: "0.vvm", styleId: 1, kind: "talk", characterName: "ずんだもん", styleName: "あまあま" },
  { character: "zundamon", style: "normal", file: "0.vvm", styleId: 3, kind: "talk", characterName: "ずんだもん", styleName: "ノーマル" },
  { character: "zundamon", style: "sexy", file: "0.vvm", styleId: 5, kind: "talk", characterName: "ずんだもん", styleName: "セクシー" },
  { character: "zundamon", style: "tsuntsun", file: "0.vvm", styleId: 7, kind: "talk", characterName: "ずんだもん", styleName: "ツンツン" },
  { character: "zundamon", style: "sasayaki", file: "5.vvm", styleId: 22, kind: "talk", characterName: "ずんだもん", styleName: "ささやき" },
  { character: "zundamon", style: "hisohiso", file: "5.vvm", styleId: 38, kind: "talk", characterName: "ずんだもん", styleName: "ヒソヒソ" },
  { character: "zundamon", style: "herohero", file: "15.vvm", styleId: 75, kind: "talk", characterName: "ずんだもん", styleName: "ヘロヘロ" },
  { character: "zundamon", style: "namidame", file: "15.vvm", styleId: 76, kind: "talk", characterName: "ずんだもん", styleName: "なみだめ" },
  { character: "zundamon", style: "amaama", file: "s0.vvm", styleId: 3001, kind: "song", characterName: "ずんだもん", styleName: "あまあま" },
  { character: "zundamon", style: "normal", file: "s0.vvm", styleId: 3003, kind: "song", characterName: "ずんだもん", styleName: "ノーマル" },
  { character: "zundamon", style: "sexy", file: "s0.vvm", styleId: 3005, kind: "song", characterName: "ずんだもん", styleName: "セクシー" },
  { character: "zundamon", style: "tsuntsun", file: "s0.vvm", styleId: 3007, kind: "song", characterName: "ずんだもん", styleName: "ツンツン" },
  { character: "zundamon", style: "hisohiso", file: "s0.vvm", styleId: 3038, kind: "song", characterName: "ずんだもん", styleName: "ヒソヒソ" },
  { character: "zundamon", style: "herohero", file: "s0.vvm", styleId: 3075, kind: "song", characterName: "ずんだもん", styleName: "ヘロヘロ" },
  { character: "zundamon", style: "namidame", file: "s0.vvm", styleId: 3076, kind: "song", characterName: "ずんだもん", styleName: "なみだめ" },
];
